version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/seniorCitizen
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
